export const applicants = [
  {
    name: "Applicant 1",
    current_position: "Position 1",
    total_experience: "5 years",
    field_of_expertise: "IT",
    address: "Address 1",
    age: 30,
    email: "applicant1@example.com",
    phone: "123-456-7890",
    linkedin: "linkedin.com/in/applicant1",
    applied_date: "2023-01-01",
    status: "Pending",
    education: "Bachelor of Science in Information Technology",
    skills: ["Java", "Spring Boot", "Microservices"],
    references: ["Reference 1", "Reference 2"],
  },
  {
    name: "Applicant 2",
    current_position: "Position 2",
    total_experience: "8 years",
    field_of_expertise: "Software Engineering",
    address: "Address 2",
    age: 35,
    email: "applicant2@example.com",
    phone: "987-654-3210",
    linkedin: "linkedin.com/in/applicant2",
    applied_date: "2023-02-15",
    status: "Accepted",
    education: "Master of Computer Science",
    skills: ["Python", "Django", "React"],
    references: ["Reference 3", "Reference 4"],
  },
  {
    name: "Applicant 3",
    current_position: "Position 3",
    total_experience: "3 years",
    field_of_expertise: "Web Development",
    address: "Address 3",
    age: 28,
    email: "applicant3@example.com",
    phone: "555-123-4567",
    linkedin: "linkedin.com/in/applicant3",
    applied_date: "2023-03-10",
    status: "Rejected",
    education: "Bachelor of Arts in Computer Science",
    skills: ["HTML", "CSS", "JavaScript"],
    references: ["Reference 5", "Reference 6"],
  },
  {
    name: "Applicant 4",
    current_position: "Position 4",
    total_experience: "10 years",
    field_of_expertise: "Data Science",
    address: "Address 4",
    age: 42,
    email: "applicant4@example.com",
    phone: "999-888-7777",
    linkedin: "linkedin.com/in/applicant4",
    applied_date: "2023-04-20",
    status: "Pending",
    education: "Ph.D. in Statistics",
    skills: ["R", "Python", "Machine Learning"],
    references: ["Reference 7", "Reference 8"],
  },
  {
    name: "Applicant 5",
    current_position: "Position 5",
    total_experience: "7 years",
    field_of_expertise: "UX/UI Design",
    address: "Address 5",
    age: 31,
    email: "applicant5@example.com",
    phone: "777-111-2222",
    linkedin: "linkedin.com/in/applicant5",
    applied_date: "2023-05-12",
    status: "Accepted",
    education: "Bachelor of Fine Arts",
    skills: ["Adobe XD", "Sketch", "Prototyping"],
    references: ["Reference 9", "Reference 10"],
  },
  {
    name: "Applicant 6",
    current_position: "Position 6",
    total_experience: "6 years",
    field_of_expertise: "Marketing",
    address: "Address 6",
    age: 29,
    email: "applicant6@example.com",
    phone: "444-555-6666",
    linkedin: "linkedin.com/in/applicant6",
    applied_date: "2023-06-01",
    status: "Pending",
    education: "Master of Business Administration",
    skills: ["Digital Marketing", "SEO", "Social Media"],
    references: ["Reference 11", "Reference 12"],
  },
  {
    name: "Applicant 7",
    current_position: "Position 7",
    total_experience: "4 years",
    field_of_expertise: "Finance",
    address: "Address 7",
    age: 27,
    email: "applicant7@example.com",
    phone: "222-333-4444",
    linkedin: "linkedin.com/in/applicant7",
    applied_date: "2023-07-10",
    status: "Rejected",
    education: "Bachelor of Commerce",
    skills: ["Financial Analysis", "Investment Banking", "Risk Management"],
    references: ["Reference 13", "Reference 14"],
  },
  {
    name: "Applicant 8",
    current_position: "Position 8",
    total_experience: "9 years",
    field_of_expertise: "Human Resources",
    address: "Address 8",
    age: 36,
    email: "applicant8@example.com",
    phone: "888-999-0000",
    linkedin: "linkedin.com/in/applicant8",
    applied_date: "2023-08-15",
    status: "Accepted",
    education: "Master of Human Resource Management",
    skills: ["Recruitment", "Employee Relations", "Performance Management"],
    references: ["Reference 15", "Reference 16"],
  },
  {
    name: "Applicant 9",
    current_position: "Position 9",
    total_experience: "2 years",
    field_of_expertise: "Sales",
    address: "Address 9",
    age: 24,
    email: "applicant9@example.com",
    phone: "111-222-3333",
    linkedin: "linkedin.com/in/applicant9",
    applied_date: "2023-09-20",
    status: "Pending",
    education: "Bachelor of Business Administration",
    skills: ["Negotiation", "Customer Relationship Management", "Cold Calling"],
    references: ["Reference 17", "Reference 18"],
  },
  {
    name: "Applicant 10",
    current_position: "Position 10",
    total_experience: "12 years",
    field_of_expertise: "Engineering",
    address: "Address 10",
    age: 45,
    email: "applicant10@example.com",
    phone: "666-777-8888",
    linkedin: "linkedin.com/in/applicant10",
    applied_date: "2023-10-05",
    status: "Accepted",
    education: "Bachelor of Engineering",
    skills: ["Mechanical Design", "CAD/CAM", "Project Management"],
    references: ["Reference 19", "Reference 20"],
  },
  {
    name: "Applicant 11",
    current_position: "Position 11",
    total_experience: "6 years",
    field_of_expertise: "IT",
    address: "Address 11",
    age: 32,
    email: "applicant11@example.com",
    phone: "123-456-7890",
    linkedin: "linkedin.com/in/applicant11",
    applied_date: "2023-11-12",
    status: "Pending",
    education: "Bachelor of Science in Computer Science",
    skills: ["JavaScript", "React", "Node.js"],
    references: ["Reference 21", "Reference 22"],
  },
  {
    name: "Applicant 12",
    current_position: "Position 12",
    total_experience: "8 years",
    field_of_expertise: "Software Engineering",
    address: "Address 12",
    age: 38,
    email: "applicant12@example.com",
    phone: "987-654-3210",
    linkedin: "linkedin.com/in/applicant12",
    applied_date: "2023-12-20",
    status: "Accepted",
    education: "Master of Science in Computer Engineering",
    skills: ["Java", "Spring", "Hibernate"],
    references: ["Reference 23", "Reference 24"],
  },
  {
    name: "Applicant 13",
    current_position: "Position 13",
    total_experience: "4 years",
    field_of_expertise: "Web Development",
    address: "Address 13",
    age: 29,
    email: "applicant13@example.com",
    phone: "555-123-4567",
    linkedin: "linkedin.com/in/applicant13",
    applied_date: "2024-01-10",
    status: "Rejected",
    education: "Bachelor of Science in Software Engineering",
    skills: ["HTML", "CSS", "JavaScript"],
    references: ["Reference 25", "Reference 26"],
  },
  {
    name: "Applicant 14",
    current_position: "Position 14",
    total_experience: "10 years",
    field_of_expertise: "Data Science",
    address: "Address 14",
    age: 41,
    email: "applicant14@example.com",
    phone: "999-888-7777",
    linkedin: "linkedin.com/in/applicant14",
    applied_date: "2024-02-15",
    status: "Pending",
    education: "Ph.D. in Data Analytics",
    skills: ["Python", "R", "Machine Learning"],
    references: ["Reference 27", "Reference 28"],
  },
  {
    name: "Applicant 15",
    current_position: "Position 15",
    total_experience: "7 years",
    field_of_expertise: "UX/UI Design",
    address: "Address 15",
    age: 30,
    email: "applicant15@example.com",
    phone: "777-111-2222",
    linkedin: "linkedin.com/in/applicant15",
    applied_date: "2024-03-01",
    status: "Accepted",
    education: "Bachelor of Fine Arts",
    skills: ["Adobe XD", "Sketch", "Wireframing"],
    references: ["Reference 29", "Reference 30"],
  },
  {
    name: "Applicant 16",
    current_position: "Position 16",
    total_experience: "6 years",
    field_of_expertise: "Marketing",
    address: "Address 16",
    age: 31,
    email: "applicant16@example.com",
    phone: "444-555-6666",
    linkedin: "linkedin.com/in/applicant16",
    applied_date: "2024-04-10",
    status: "Rejected",
    education: "Master of Business Administration",
    skills: ["Digital Marketing", "SEO", "Content Creation"],
    references: ["Reference 31", "Reference 32"],
  },
  {
    name: "Applicant 17",
    current_position: "Position 17",
    total_experience: "4 years",
    field_of_expertise: "Finance",
    address: "Address 17",
    age: 27,
    email: "applicant17@example.com",
    phone: "222-333-4444",
    linkedin: "linkedin.com/in/applicant17",
    applied_date: "2024-05-20",
    status: "Pending",
    education: "Bachelor of Commerce",
    skills: ["Financial Analysis", "Investment Banking", "Risk Management"],
    references: ["Reference 33", "Reference 34"],
  },
  {
    name: "Applicant 18",
    current_position: "Position 18",
    total_experience: "9 years",
    field_of_expertise: "Human Resources",
    address: "Address 18",
    age: 35,
    email: "applicant18@example.com",
    phone: "888-999-0000",
    linkedin: "linkedin.com/in/applicant18",
    applied_date: "2024-06-05",
    status: "Accepted",
    education: "Master of Human Resource Management",
    skills: ["Recruitment", "Employee Relations", "Training and Development"],
    references: ["Reference 35", "Reference 36"],
  },
  {
    name: "Applicant 19",
    current_position: "Position 19",
    total_experience: "2 years",
    field_of_expertise: "Sales",
    address: "Address 19",
    age: 25,
    email: "applicant19@example.com",
    phone: "111-222-3333",
    linkedin: "linkedin.com/in/applicant19",
    applied_date: "2024-07-12",
    status: "Pending",
    education: "Bachelor of Business Administration",
    skills: [
      "Negotiation",
      "Customer Relationship Management",
      "Sales Strategy",
    ],
    references: ["Reference 37", "Reference 38"],
  },
  {
    name: "Applicant 20",
    current_position: "Position 20",
    total_experience: "12 years",
    field_of_expertise: "Engineering",
    address: "Address 20",
    age: 43,
    email: "applicant20@example.com",
    phone: "666-777-8888",
    linkedin: "linkedin.com/in/applicant20",
    applied_date: "2024-08-18",
    status: "Accepted",
    education: "Bachelor of Engineering",
    skills: ["Mechanical Design", "CAD/CAM", "Project Management"],
    references: ["Reference 39", "Reference 40"],
  },
];
