"use client";
import { Box, StyledEngineProvider, Toolbar } from "@mui/material";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledEngineProvider injectFirst>
        <Box sx={{ display: "flex" }}>
          <Header />
          <Box
            component="main"
            sx={{ p: 3 }}
            style={{
              backgroundColor: "white",
              color: "black",
              overflow: "none",
              width: '100%',
              minHeight: '100vh',
            }}
          >
            <Toolbar />
            <div style={{width:'match-parent'}}>
            {children}
            </div>
            
          </Box>
        </Box>
      </StyledEngineProvider>
    </html>
  );
}
